# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e157edc79c674b86c72b23c539fee2220847158ae1e606134dce5f2718280c418c2c6c1b5c374530b0fdccf99ba3907aedccc9e636198026faa476eda28e7eb0

test:
  secret_key_base: 87d0bfb4ba19d2839b98e8cefbf4a01320eac76da6f02791cf8dafd10b77718cf63c808605bed07b499eefab99b93374142a4ede949566133b339cee75d6054c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
